### ISSUE TITLE
Update and distribute?

### ISSUE THREAD

**Issue by yaxu** [gonzaloflirt/link-python#2]
Hello, this package is still working great thanks! There is an update to the link library though, would you in principle accept a PR to update it, and are you interested in distributing the result on https://pypi.org/ so it's easily installed with `pip`?

**Comment by gonzaloflirt** [comment]
@yaxu @munshkr Thanks! I didn't know anyone is using this. (I haven't been for years)
I cherry-picked the updates from https://github.com/gonzaloflirt/link-python/pull/4.
I didn't merge the entire branch because I'm not sure about publishing this on pypi. I don't really have an interest to maintain the lib there because I don't use it a lot.

**Comment by gonzaloflirt** [comment]
BTW. If someone would like to maintain a fork and pypi, I'd happily refer to it from here.

**Comment by yaxu** [comment]
Thanks a lot! It seems @munshkr has done a release from his fork here https://pypi.org/project/LinkPython/

**Comment by munshkr** [comment]
> BTW. If someone would like to maintain a fork and pypi, I'd happily refer to it from here.

Thank you! I'm willing to do minimal maintainance on the package, so if you're OK with adding a reference to my fork, that would be great :)
